title: "Oliver Brufal"

remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

photo: /assets/img/me.jpg   
email: o.l.r.brufal.de.melgarejo[at]rug.nl  
cv_url: /assets/cv_OB.pdf     

url: "https://brufalo.github.io"
baseurl: ""
